notifications:
  email: false

env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

addons:
  apt:
    packages:
    - bash
    - curl

install: true

script:
- export root=$(pwd)
- bash test.sh
